# This file defines a workflow that runs tests and deploys your application on push to the main branch

name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Build the solution
        run: dotnet build --configuration Release
      - name: Run unit tests
        run: dotnet test --configuration Release
      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: **/bin/Release/**

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()  # Only deploy if build and tests pass
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: .
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Replace with your Azure credentials secret
      - name: Deploy to Azure App Service
        uses: azure/webdeploy@v1
        with:
          name: your-app-service-name
          package: .
          slot-label: Staging  # Optional slot for deployment staging
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}  # Replace with your publish profile secret

