# This file defines a workflow with separate jobs for build, test, publish, and deploy

name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Build the solution
        run: dotnet build --configuration Release
      - name: Publish build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: .
      - name: Run unit tests
        run: dotnet test --configuration Release

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: .
      # Add your specific publishing steps here (e.g., NuGet package creation, versioning)

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: .
      # Add your specific deployment steps here (e.g., Azure deployment using downloaded artifacts)

